models.py
from app import db
from datetime import datetime
import re

from flask_security import UserMixin, RoleMixin

def slagify(s):
    pattern = r'[^\w+]'
    return re.sub(pattern, '-', s)

post_tags = db.Table('post_tags',
        db.Column('post_id', db.Integer, db.ForeignKey('post.id')),
        db.Column('tag_id', db.Integer, db.ForeignKey('tag.id'))
    )


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(140))
    slug = db.Column(db.String(140), unique=True)
    body = db.Column(db.Text)
    created = db.Column(db.DateTime, default=datetime.now())

    def __init__(self, *args, **kwargs):
        super(Post, self).__init__(*args, **kwargs)
        self.generate_slug()

    tags = db.relationship('Tag', secondary=post_tags, backref=db.backref('posts', lazy='dynamic'))

    def generate_slug(self):
        if self.title:
            self.slug = slagify(self.title)

    # чтобы можно было через консоль выводить данные из таблицы
    def __repr__(self):
        return '{}'.format(self.title)


class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    slug = db.Column(db.String(100))

    def __init__(self, *args, **kwargs):
        super(Tag, self).__init__(*args, **kwargs)
        self.slug = slagify(self.name)

    # чтобы можно было через консоль выводить данные из таблицы
    def __repr__(self):
        return '{}'.format(self.name)


roles_users = db.Table('roles_users',
        db.Column('user_id', db.Integer(), db.ForeignKey('user.id')),
        db.Column('role_id', db.Integer(), db.ForeignKey('role.id'))
    )


# Flask-Security
class User(db.Model, UserMixin):
    id = db.Column(db.Integer(), primary_key=True)
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(255))
    active = db.Column(db.Boolean())
    roles = db.relationship('Role', secondary=roles_users, backref=db.backref('users', lazy='dynamic'))


class Role(db.Model, RoleMixin):
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(100), unique=True)
    description = db.Column(db.String(255))

posts/forms.py
from wtforms import Form, StringField, TextAreaField


class PostForm(Form):
    title = StringField('Title')
    body = TextAreaField('Body')

app.py
from flask import Flask, redirect, url_for, request
from config import Configuration
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager
from flask_admin import Admin
from flask_admin import AdminIndexView
from flask_admin.contrib.sqla import ModelView
from flask_security import SQLAlchemyUserDatastore
from flask_security import Security
from flask_security import current_user

app = Flask(__name__)
app.config.from_object(Configuration)

db = SQLAlchemy(app)

migrate = Migrate(app, db)
manager = Manager(app)
manager.add_command('db', MigrateCommand)

# ADMIN
from models import *

class AdminMixin():
    def is_accessible(self):
        return current_user.has_role('admin')

    def inaccessible_callback(self, name, **kwargs):
        return redirect(url_for('security.login', next=request.url))

class BaseModelView(ModelView):
    def on_model_change(self, form, model, is_created):
        model.generate_slug()
        return super(BaseModelView, self).on_model_change(form, model, is_created)

class AdminView(AdminMixin, ModelView):
    pass

class HomeAdminView(AdminMixin, AdminIndexView):
    pass

class PostAdminView(AdminMixin, BaseModelView):
    form_columns = ['title', 'body', 'tags']

class TagAdminView(AdminMixin, BaseModelView):
    form_columns = ['name', 'posts']

admin = Admin(app, 'FlaskAdmin', url='/', index_view=HomeAdminView(name='Home'))
admin.add_view(PostAdminView(Post, db.session))
admin.add_view(TagAdminView(Tag, db.session))

# Flask-Security
user_datastore = SQLAlchemyUserDatastore(db, User, Role)
security = Security(app, user_datastore)

main.py
from app import app
from app import db

from posts.blueprint import posts

import view

app.register_blueprint(posts, url_prefix='/blog')

if __name__ == '__main__':
    app.run()

posts/blueprint.py
from flask import Blueprint, render_template, request, redirect, url_for

from models import Post, Tag
from .forms import PostForm
from app import db

from flask_security import login_required


posts = Blueprint('posts', __name__, template_folder='templates')

# http://localhost:5000/blog/create
@posts.route('/create', methods=['POST', 'GET'])
@login_required
def create_post():
    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']

        try:
            post = Post(title=title, body=body)
            db.session.add(post)
            db.session.commit()
        except:
            print('Какая то ошибка при отправке формы')

        return redirect( url_for('posts.index') )
    
    form = PostForm()
    return render_template('posts/create_post.html', form=form)


# http://localhost:5000/blog/<slug>/edit/
@posts.route('/<slug>/edit/', methods=['POST', 'GET'])
@login_required
def edit_post(slug):
    post = Post.query.filter(Post.slug==slug).first_or_404()
    if request.method == 'POST':
        form = PostForm(formdata=request.form, obj=post)
        form.populate_obj(post)
        db.session.commit()
        return redirect(url_for('posts.post_detail', slug=post.slug))

    form = PostForm(obj=post)
    return render_template('posts/edit_post.html', post=post, form=form)


# http://localhost:5000/blog/
@posts.route('/')
def index():
    q = request.args.get('q')
    
    page = request.args.get('page')

    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    if q:
        posts = Post.query.filter(Post.title.contains(q) | Post.body.contains(q))
    # desc() сортировка по убыванию
    else:
        posts = Post.query.order_by(Post.created.desc())

    pages = posts.paginate(page=page, per_page=5)

    return render_template('posts/index.html', posts=posts, pages=pages)


# http://localhost:5000/blog/<slag>
@posts.route('/<slug>')
def post_detail(slug):
    post = Post.query.filter(Post.slug==slug).first_or_404()
    tags = post.tags
    return render_template('posts/post_detail.html', post=post, tags=tags)


# http://localhost:5000/blog/tag/<slag>
@posts.route('/tag/<slug>')
def tag_detail(slug):
    tag = Tag.query.filter(Tag.slug==slug).first_or_404()
    posts = tag.posts.all()
    return render_template('posts/tag_detail.html', tag=tag, posts=posts)

posts/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}
    Create new post
{% endblock %}

{% block content_title %}
    Post
{% endblock %}

{% block content %}

    <div class="row mt-3">
        <div class="col-md-6">
            <form action="{{ url_for('posts.create_post') }}" method="POST">
                {% for field in form %}
                    <div class="form-group">
                        {{ field.label(class='control-label') }}
                        {{ field(class='form-control') }}
                    </div>
                {% endfor %}
                <div class="mt-2">
                    <button type="submit" class="btn btn-primary">Создать</button>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

posts/templates/posts/edit_post.html
{% extends 'base.html' %}

{% block title %}
    Edit new post
{% endblock %}

{% block content_title %}
    Post
{% endblock %}

{% block content %}

    <div class="row mt-3">
        <div class="col-md-6">
            <form action="{{ url_for('posts.edit_post', slug=post.slug) }}" method="POST">
                {% for field in form %}
                    <div class="form-group">
                        {{ field.label(class='control-label') }}
                        {{ field(class='form-control') }}
                    </div>
                {% endfor %}
                <div class="mt-2">
                    <button type="submit" class="btn btn-primary">Изменить</button>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
Blueprint page
{% endblock %}

{% block content_title %}
Posts
{% endblock %}

{% block content %}

{% for post in pages.items %}
<p>
    <a href="{{ url_for('posts.post_detail', slug=post.slug) }}">
        {{ post.title }}
    </a>
</p>
{% endfor %}

<div class="row mt-3">
    <div class="col">
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
                <li
                    class="page-item {% if not pages.has_prev %}disabled{% endif %}"
                >
                    <a
                        class="page-link"
                        href="./?page={{ pages.prev_num }}"
                    >
                        Назад
                    </a>
                </li>
                {% for page in pages.iter_pages() %}
                <li class="page-item {% if page == pages.page %}active{% endif %}">
                    <a class="page-link" href="./?page={{ page }}">{{ page }}</a>
                </li>
                {% endfor %}
                <li
                    class="page-item {% if not pages.has_next %}disabled{% endif %}"
                >
                    <a
                        class="page-link"
                        href="./?page={{ pages.next_num }}"
                    >
                        Вперёд
                    </a>
                </li>
            </ul>
        </nav>
    </div>
</div>

{% endblock %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content_title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    {{ post.body }}
    <div class="tags">
        {% for tag in tags %}
            <a
              href="{{ url_for('posts.tag_detail', slug=tag.slug) }}"
            >
                <span class="badge badge-primary">{{ tag.name }}</span>
            </a>
        {% endfor %}
    </div>
{% endblock %}

posts/templates/posts/tag_detail.html
{% extends 'base.html' %}

{% block title %}
    {{ tag.name }} posts
{% endblock %}

{% block content_title %}
    Posts for "{{ tag.name }}" tag:
{% endblock %}

{% block content %}
    {% for post in posts %}
      <div class="post">
        <a
          href="{{ url_for('posts.post_detail', slug=post.slug) }}"
        >
          {{ post.title }}
        </a>
      </div>
    {% endfor %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link
    rel="stylesheet"
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
    crossorigin="anonymous"
  />
  <title>
    {% block title %}
    
    {% endblock %} | Flask app
  </title>
</head>

<body>

  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container">
      <a class="navbar-brand" href="{{ url_for('index') }}">Flask</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('posts.index') }}">Блог<span class="sr-only">(current)</span></a>
          </li>
          <!-- <li class="nav-item">
            <a class="nav-link" href="{{ url_for('posts.create_post') }}">Создать</a>
          </li> -->
          {% if current_user.has_role('admin') %}
          <li class="nav-item">
            <a class="nav-link" href="/admin">Админ</a>
          </li>
          {% endif %}
        </ul>
        <form class="form-inline my-2 my-lg-0" method="GET">
          <input
            class="form-control mr-sm-2"
            type="search"
            placeholder="Поиск ..."
            aria-label="Search"
            name="q"
            value="{{ request.args.get(q, '') }}"
          />
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Поиск</button>
        </form>
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="/login">Войти</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    <div class="row">
      <div class="col">
        <h1>
          {% block content_title %}
    
          {% endblock %}
        </h1>
        {% block content %}
    
        {% endblock %}
      </div>
    </div>
  </div>

  <script
    src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous">
  </script>

  <script
    src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous">
  </script>

  <script
    src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous">
  </script>

</body>

</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}
    Index page
{% endblock %}

{% block content_title %}
    Index page
{% endblock %}

{% block content %}
    Some content
{% endblock %}

templates/security/_messages.html
{%- with messages = get_flashed_messages(with_categories=true) -%}
  {% if messages %}
    <div class="flashes">
    {% for category, message in messages %}
      <div class="alert alert-{{ category }}">{{ message }}</div>
    {% endfor %}
    </div>
  {% endif %}
{%- endwith %}

templates/security/login_user.html
{% extends 'base.html' %}

{% block content %}
<div class="row justify-content-center">
  <div class="col-6">
    {% from "security/_macros.html" import render_field_with_errors, render_field %}
    {% include "security/_messages.html" %}
    <h1 class="mt-3">
      {% block title %}
      {{ _('Login') }}
      {% endblock %}
    </h1>
    <div class="form-group mt-3">
      <form action="{{ url_for_security('login') }}" method="POST" name="login_user_form">
        {{ login_user_form.hidden_tag() }}
        {{ render_field_with_errors(login_user_form.email, class='form-control') }}
        {{ render_field_with_errors(login_user_form.password, class='form-control') }}
        {{ render_field_with_errors(login_user_form.remember, class='defaultCheck1') }}
        {{ render_field(login_user_form.next) }}
        {{ render_field(login_user_form.submit, class='btn btn-success') }}
      </form>
    </div>
    {% include "security/_menu.html" %}
  </div>
</div>
{% endblock %}